name: Deploy Static Content to Pages

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          path: master

      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop
          path: develop

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.6.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.8.0'

      - name: Clean install dependencies (Master)
        run: |
          rm -rf master/node_modules
          pnpm install --no-frozen-lockfile
        working-directory: master

      - name: Clean install dependencies (Develop)
        run: |
          rm -rf develop/node_modules
          pnpm install --no-frozen-lockfile
        working-directory: develop

      - name: Build Master Production
        run: npm run build-github-master
        working-directory: master

      - name: Build Develop Production
        run: npm run build-github-develop
        working-directory: develop

      - name: Create Dist Folder
        run: mkdir dist

      - name: Copy Master Build
        run: cp -r master/dist/* dist/

      - name: Copy Develop Build
        run: cp -r develop/dist/* dist/develop/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4